import type { Category } from './types'

const parent = (id: string, name: string, sortOrder: number): Category => ({
  id,
  parentId: null,
  name,
  enabled: true,
  sortOrder,
  isBuiltin: true,
  isDeleted: false
})

const child = (parentId: string, id: string, name: string, sortOrder: number): Category => ({
  id,
  parentId,
  name,
  enabled: true,
  sortOrder,
  isBuiltin: true,
  isDeleted: false
})

export const defaultCategories: Category[] = [
  parent('food', '餐饮', 10),
  child('food', 'food-breakfast', '早餐', 11),
  child('food', 'food-lunch', '午餐', 12),
  child('food', 'food-dinner', '晚餐', 13),
  child('food', 'food-takeout', '外卖', 14),
  child('food', 'food-snack', '零食饮料', 15),
  child('food', 'food-coffee', '咖啡茶饮', 16),
  parent('transport', '交通', 20),
  child('transport', 'transport-public', '公交地铁', 21),
  child('transport', 'transport-taxi', '打车网约车', 22),
  child('transport', 'transport-fuel', '加油充电', 23),
  child('transport', 'transport-parking', '停车', 24),
  child('transport', 'transport-train', '高铁飞机', 25),
  parent('housing', '住房', 30),
  child('housing', 'housing-rent', '房租', 31),
  child('housing', 'housing-property', '物业', 32),
  child('housing', 'housing-water', '水费', 33),
  child('housing', 'housing-electricity', '电费', 34),
  child('housing', 'housing-gas', '燃气', 35),
  child('housing', 'housing-network', '网络通信', 36),
  child('housing', 'housing-repair', '家居维修', 37),
  parent('shopping', '日用购物', 40),
  child('shopping', 'shopping-daily', '日用品', 41),
  child('shopping', 'shopping-clothes', '服饰鞋包', 42),
  child('shopping', 'shopping-digital', '数码电器', 43),
  child('shopping', 'shopping-home', '家居用品', 44),
  child('shopping', 'shopping-pet', '宠物用品', 45),
  parent('leisure', '娱乐休闲', 50),
  child('leisure', 'leisure-movie', '电影演出', 51),
  child('leisure', 'leisure-game', '游戏', 52),
  child('leisure', 'leisure-sport', '运动健身', 53),
  child('leisure', 'leisure-travel', '旅游度假', 54),
  child('leisure', 'leisure-hobby', '兴趣爱好', 55),
  parent('health', '医疗健康', 60),
  child('health', 'health-doctor', '挂号就医', 61),
  child('health', 'health-medicine', '药品', 62),
  child('health', 'health-care', '保健', 63),
  child('health', 'health-dental', '牙科眼科', 64),
  parent('education', '教育成长', 70),
  child('education', 'education-course', '课程培训', 71),
  child('education', 'education-book', '书籍资料', 72),
  child('education', 'education-exam', '考试证书', 73),
  parent('social', '社交人情', 80),
  child('social', 'social-dining', '聚餐请客', 81),
  child('social', 'social-gift', '礼物红包', 82),
  child('social', 'social-wedding', '婚礼寿宴', 83),
  parent('finance', '金融服务', 90),
  child('finance', 'finance-fee', '手续费', 91),
  child('finance', 'finance-insurance', '保险', 92),
  child('finance', 'finance-subscription', '会员订阅', 93),
  child('finance', 'finance-tax', '利息税费', 94),
  parent('other', '其他', 100),
  child('other', 'other-uncategorized', '未分类', 101),
  child('other', 'other-temporary', '临时支出', 102)
]
